"CREATE UNIQUE INDEX camaras_inventario_id_key ON public.camaras USING btree (inventario_id)"
"CREATE UNIQUE INDEX camaras_numero_camara_key ON public.camaras USING btree (numero_camara)"
"CREATE UNIQUE INDEX permisos_rol_rol_id_modulo_permiso_key ON public.permisos_rol USING btree (rol_id, modulo, permiso)"
"CREATE UNIQUE INDEX roles_nombre_key ON public.roles USING btree (nombre)"
"CREATE UNIQUE INDEX usuarios_email_key ON public.usuarios USING btree (email)"
"CREATE UNIQUE INDEX sitios_inventario_id_key ON public.sitios USING btree (inventario_id)"
"CREATE INDEX idx_sitios_inventario ON public.sitios USING btree (inventario_id)"
"CREATE INDEX idx_sitios_zona ON public.sitios USING btree (zona)"
"CREATE INDEX idx_sitios_estado ON public.sitios USING btree (estado)"
"CREATE INDEX idx_sitios_validacion ON public.sitios USING btree (validacion_estado)"
"CREATE INDEX idx_sitios_val_sitio ON public.sitios_validacion USING btree (sitio_id)"
"CREATE INDEX idx_sitios_val_estado ON public.sitios_validacion USING btree (estado)"
"CREATE INDEX idx_sitios_evid_sitio ON public.sitios_evidencia_fotografica USING btree (sitio_id)"
"CREATE INDEX idx_sitios_mant_sitio ON public.sitios_mantenimiento USING btree (sitio_id)"
"CREATE INDEX idx_sitios_mant_estado ON public.sitios_mantenimiento USING btree (estado)"
"CREATE INDEX idx_sitios_mant_fecha ON public.sitios_mantenimiento USING btree (fecha_programada)"